config/routes.rb
Lawdingo::Application.routes.draw do

     namespace :admin do
       resources :lawyers, :controller =>'firms'
     end

   root :to => 'firms#index'

end

app/models/lawyer.rb
class Lawyer < ActiveRecord::Base
  has_attached_file :photo,
                    :styles => { :medium => "200x200>", :thumb => "100x100>" },
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :path => ":attachment/:id/:style.:extension",
                    :bucket => 'lawdingo'
end

app/controllers/admin/firms_controller.rb
class Admin::FirmsController < ApplicationController

  def new
    @lawyer = Lawyer.new
  end

  def create
    @lawyer = Lawyer.new(params[:lawyer])
    if @lawyer.save
      redirect_to root_path, :notice =>'Lawyer Added Successfully!'
    else
      render :action =>:new
    end
  end

  def edit
    begin
      @lawyer = Lawyer.find params[:id]
    rescue
      redirect_to root_path, :notice =>'No Lawyer Found!'
    end
  end

  def update
    @lawyer = Lawyer.find params[:id]
    if @lawyer.update_attributes(params[:lawyer])
      redirect_to root_path, :notice =>'Lawyer Updated Successfully!'
    else
      render :action =>:edit
    end
  end

  def destroy    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController

  def index
    @lawyers = Lawyer.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/firms/_form.html.erb
<%= form_for ['admin', @lawyer], :method=>'post' do |f| %>
  Full Name :<br/>
  <%= f.text_field :full_name %> <br/>
  Skype : <br/>
  <%= f.text_field :skype %> <br/>
  Photo : <br/>
  <%= f.file_field :photo %> <br/>
  Bar Memberships: <br/>
  <%= f.text_area :bar_memberships, :size =>'50x3' %><br/>
  Areas of Expertise: <br/>
  <%= f.text_area :areas_of_expertise, :size =>'50x3' %><br/>
  Alma Maters: <br/>
  <%= f.text_area :alma_maters, :size =>'50x3' %> <br/>
  <%= f.submit @lawyer.new_record? ? 'Add Profile' : 'Update Profile' %>
<% end %>

app/views/admin/firms/edit.html.erb
Update Lawyer Profile<br/>
<%= render :partial =>'form' %>

app/views/admin/firms/new.html.erb
<h3>Add New Lawyer Profile</h3>
<%= render :partial =>'form' %>

app/views/firms/_lawyer.html.erb
<div class="list_item">
  <div style="float: left;width:105px; text-align:center;">

      <%= image_tag lawyer.photo.url(:thumb),:style=>"border:solid #000 2px;" %>

  </div>
  <div style="margin-left:110px;">
    <strong><%= lawyer.full_name %></strong> <br/>
    <strong>Bar Memberships: </strong><%= lawyer.bar_memberships %><br/>
    <strong>Areas of Expertise: </strong><%= lawyer.areas_of_expertise %><br/>
    <strong>Alma Maters: </strong><%= lawyer.alma_maters %><br/>

   <!--
Skype 'My status' button
http://www.skype.com/go/skypebuttons
-->
<script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script>
<a href="skype:<%= lawyer.skype %>?call"><img src="http://mystatus.skype.com/bigclassic/<%= lawyer.skype %>" style="border:none;" width="120" height="30" alt="My status" /></a>


  </div>
  <div style="clear: both;"></div>
</div>

app/views/firms/index.html.erb
<h3>Lawdingo.com : Talk to a lawyer over video chat</h3>
<%= render :partial =>'/firms/lawyer', :collection =>@lawyers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Law Dingo</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="page">
      <!--div id="header">
        <div id="hleft">
          <h2><%#= link_to "Law Dingo", root_path %></h2>
        </div>
        <div id="hright">
          <%#= link_to "Add New Lawyer Profile", new_admin_lawyer_path, :title =>'Add New Profile!' %>
        </div>
      </div-->
      <div id="main_content">
      <div class="left">
      </div>
      <div class="right">
       <% if flash[:notice] %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= yield %>
      </div>
      </div>
    <!--div id="footer">
    </div-->
    </div>
      </body>
</html>